export const musicList = [
    {
        banner: "../assets/music-image/saiba.jpeg",
        songName: "Sahiba",
        singer: "Aditya Rikhar",
        source: "../assets/audios/Sahiba(PagaiWorld.com).mp3",
        album: null,
        listeners: null,
        category: null,
    },
    {
        banner: "../assets/music-image/ik-kudi.jpeg",
        songName: "Ik Kudi",
        singer: "Arpit Bala & Wolf.Cryman",
        source: "../assets/audios/Ik Kudi(PagaiWorld.com).mp3",
        album: null,
        listeners: null,
        category: null,
    },

    //recently played
    {
        banner: "../assets/music-image/obsessed.jpeg",
        songName: "Obsessed",
        singer: "Riar Saab & Abhijay Sharma",
        source: "../assets/audios/Obsessed-128kbps.mp3",
        album: null,
        listeners: null,
        category: "recentlyPlayed",
    },
    {
        banner: "../assets/music-image/Tauba-Tauba.jpeg",
        songName: "Tauba Tauba",
        singer: "Karan Aujla",
        source: "../assets/audios/Tauba Tauba-128kbps.mp3",
        album: null,
        listeners: null,
        category: "recentlyPlayed",
    },
    {
        banner: "../assets/music-image/players.jpeg",
        songName: "Players",
        singer: "Badshah & Karan Aujla",
        source: "../assets/audios/Players-badshah.mp3",
        album: null,
        listeners: null,
        category: "recentlyPlayed",
    },
    {
        banner: "../assets/music-image/Heeriye.jpeg",
        songName: "Heeriye",
        singer: "Arijit Singh & Jasleen Royal",
        source: "../assets/audios/Heeriye feat Arijit Singh(PagaiWorld.com).mp3",
        album: null,
        listeners: null,
        category: "recentlyPlayed",
    },
    {
        banner: "../assets/music-image/Still Rollin.jpeg",
        songName: "Still Rollin",
        singer: "Shubh",
        source: "../assets/audios/Still Rollin-128kbps.mp3",
        album: null,
        listeners: null,
        category: "recentlyPlayed",
    },
    {
        banner: "../assets/music-image/dhundhala.jpeg",
        songName: "Dhundhala",
        singer: "Talwiinder, and Yashraj",
        source: "../assets/audios/Dhundhala(PagaiWorld.com).mp3",
        album: null,
        listeners: null,
        category: "recentlyPlayed",
    },

    //top 10 songs
    {
        rank: 1,
        image: "assets/music-image/Still Rollin.jpeg",
        songName: "Still Rollin",
        artist: "Shubh",
        album: "Still Rollin",
        views: 1502255,
        time: "2:38",
    },
    {
        rank: 2,
        image: "assets/music-image/apna-bana-le.jpg",
        songName: "Apna Bana Le",
        artist: "Arijit Singh",
        album: "Bhediya",
        views: 3205541,
        time: "3:51",
    },
    {
        rank: 3,
        image: "assets/music-image/blinding-lights.jpeg",
        songName: "Blinding Lights",
        artist: "The Weeknd",
        album: "After Hours",
        views: 620002155,
        time: "3:20",
    },
    {
        rank: 4,
        image: "assets/music-image/no-love.jpeg",
        songName: "No Love",
        artist: "Shubh",
        album: "Singles",
        views: 8022145,
        time: "2:50",
    },
    {
        rank: 5,
        image: "assets/music-image/attention.jpeg",
        songName: "Attention",
        artist: "Charlie Puth",
        album: "Voicenotes",
        views: 540125500,
        time: "3:27",
    },
    {
        rank: 6,
        image: "assets/music-image/kesariya.jpeg",
        songName: "Kesariya",
        artist: "Arijit Singh",
        album: "Brahmāstra",
        views: 4202544,
        time: "4:28",
    },
    {
        rank: 7,
        image: "assets/music-image/goat.jpeg",
        songName: "GOAT",
        artist: "Diljit Dosanjh",
        album: "GOAT",
        views: 11225544,
        time: "3:15",
    },
    {
        rank: 8,
        image: "assets/music-image/shape-of-you.jpeg",
        songName: "Shape of You",
        artist: "Ed Sheeran",
        album: "Divide",
        views: 900221554,
        time: "3:53",
    },
    {
        rank: 9,
        image: "assets/music-image/raataan-lambiyan.jpeg",
        songName: "Raataan Lambiyan",
        artist: "Jubin Nautiyal & Asees Kaur",
        album: "Shershaah",
        views: 51002544,
        time: "3:50",
    },
    {
        rank: 10,
        image: "assets/music-image/industry-baby.jpeg",
        songName: "Industry Baby",
        artist: "Lil Nas X & Jack Harlow",
        album: "Montero",
        views: 780214125,
        time: "3:32",
    },
];